# Generated by Django 3.2.7 on 2021-10-01 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_source', models.ImageField(upload_to='images/src/', verbose_name='source image')),
                ('image_target', models.ImageField(upload_to='images/trg/', verbose_name='target image')),
                ('convert_time', models.DateTimeField(auto_now_add=True, verbose_name='convert time')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'conversion',
                'verbose_name_plural': 'conversions',
            },
        ),
    ]
