# Generated by Django 3.2.6 on 2021-08-29 22:17

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'This username is already taken.'}, max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='username'),
        ),
    ]
